version: '3'

services:
  user-service:
    build: ./user-service
    ports:
      - "8001:8001"

  product-service:
    build: ./product-service
    ports:
      - "8002:8002"

  cart-service:
    build: ./cart-service
    ports:
      - "8003:8003"



#If you want to run all services together, you can use Docker Compose. Here’s an example docker-compose.yml:

#To start the services:
#docker-compose up --build
#SThis will build and run all three services simultaneously and expose them on their respective ports (8001, 8002, 8003).

